name: "checkIngressDiff"
description: "Check if Ingress files are identical"
author: "fantasyflip"

inputs:
  namespace:
    required: true
    description: "Namespace for Kubernetes-files"
  deployment-path:
    required: true
    description: "Path to the deployment files in the source repository"

runs:
  using: "node16"
  main: "checkIngressDiff.js"
